package com.prototype.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.prototype.model.enums.EquipmentStatus;
import com.prototype.model.enums.EquipmentType;

/**
 * Entity that represents a biomedical equipment item registered in the system.
 * 
 * <p>
 * This class extends {@link Equipment} and adds fields specific to
 * biomedical devices, such as risk classification and calibration
 * certification. These attributes provide the necessary traceability required
 * for biomedical equipment inside institutional environments.
 * </p>
 *
 * <p>
 * Instances are stored in the {@code biomedical_equiments} table.
 * </p>
 */
@Entity
@Table(name = "biomedical_equipments")
public class BiomedicalEquipment extends Equipment {

    /**
     * Risk classification assigned to the biomedical device. This value is used
     * to identify the regulatory or safety category of the equipment.
     */
    @Column(name = "risk_class")
    private String riskClass;

    /**
     * Reference to the calibration certificate associated with the biomedical
     * device. This certificate verifies the operational precision of the
     * equipment.
     */
    @Column(name = "calibration_cert")
    private String calibrationCert;

    /**
     * Default constructor required by JPA.
     */
    public BiomedicalEquipment() {
    }

    /**
     * Deprecated constructor including the entity ID.
     *
     * <p>
     * This constructor is kept for compatibility but should not be used in
     * new code, as IDs are man
     * 
     * /**
     * Creates a biomedical equipment instance without specifying an ID, which
     * will be generated by the database.
     *
     * @param serial          device serial number
     * @param brand           device brand
     * @param model           device model
     * @param type            general equipment type
     * @param state           operational status
     * @param imagePath       path or reference to the stored image
     * @param riskClass       biomedical risk classification
     * @param calibrationCert associated calibration certificate
     * @param provider        equipment provider
     */
    public BiomedicalEquipment(String serial, String brand, String model, EquipmentType type,
            EquipmentStatus state, String imagePath,
            String riskClass, String calibrationCert, Provider provider) {
        super(serial, brand, model, type, state, imagePath, provider);
        this.riskClass = riskClass;
        this.calibrationCert = calibrationCert;
    }

    /**
     * Returns the assigned risk classification of the biomedical device.
     *
     * @return risk class
     */
    public String getRiskClass() {
        return riskClass;
    }

    /**
     * Updates the risk classification of the biomedical device.
     *
     * @param riskClass new risk class
     */
    public void setRiskClass(String riskClass) {
        this.riskClass = riskClass;
    }

    /**
     * Returns the reference to the calibration certificate of the device.
     *
     * @return calibration certificate reference
     */
    public String getCalibrationCert() {
        return calibrationCert;
    }

    /**
     * Updates the calibration certificate reference.
     *
     * @param calibrationCert new certificate reference
     */
    public void setCalibrationCert(String calibrationCert) {
        this.calibrationCert = calibrationCert;
    }

    /**
     * Returns a textual representation of the biomedical equipment, including
     * inherited fields and biomedical-specific attributes.
     */
    @Override
    public String toString() {
        return super.toString() + " BiomedicalEquipment {riskClass='" + riskClass +
                "', calibrationCert='" + calibrationCert + "'}";
    }
}
