package com.prototype.model.entities;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.CreationTimestamp;

import com.prototype.model.enums.RequestStatus;

/**
 * Entity that represents a request to authorize the entry of a technological
 * or biomedical equipment item into the institution.
 *
 * <p>This class stores information about who requested the entry, which
 * equipment is involved, the purpose of the request, the timestamp when the
 * request was created, and its current processing status.</p>
 *
 * <p>Instances are persisted in the {@code entry_request} table.</p>
 */
@Entity
@Table(name = "entry_request")
public class EntryRequest {

    /** Placeholder static reference used elsewhere in the application. */
    public static Class<Long> classS;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Equipment associated with the entry request.
     *
     * <p>Uses LAZY loading to avoid unnecessary data retrieval unless the
     * equipment is explicitly accessed.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(nullable = false, name = "id_equipment")
    private Equipment equipment;

    /**
     * Person who is requesting the equipment entry.
     *
     * <p>Also loaded lazily and linked via a foreign key managed by JPA.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    private Person requester;

    /**
     * Stated purpose or justification for bringing the equipment into the facility.
     *
     * <p>Limited to 100 characters.</p>
     */
    @Column(nullable = false, length = 100)
    private String purpose;

    /**
     * Timestamp automatically assigned when the request is created.
     *
     * <p>This value is generated by Hibernate through {@code @CreationTimestamp}.</p>
     */
    @CreationTimestamp
    @Column(name = "requested_at")
    private LocalDateTime requestedAt;

    /**
     * Current processing status of the entry request.
     *
     * <p>Stored as a {@code String} representation of the {@link RequestStatus} enum.</p>
     */
    @Enumerated(EnumType.STRING)
    private RequestStatus status;

    /**
     * Default constructor required by JPA.
     */
    public EntryRequest() {
    }

    /**
     * Deprecated full constructor including the ID.
     *
     * <p>Kept only for compatibility. New code should use the constructor
     * without the ID, as identifiers are generated by the database.</p>
     *
     * @param id            request ID
     * @param equipment     associated equipment
     * @param requester     requesting person
     * @param purpose       purpose of the request
     * @param requestedAt   creation timestamp
     * @param status        current status
     */
    @Deprecated
    public EntryRequest(Long id, Equipment equipment, Person requester, String purpose, LocalDateTime requestedAt,
            RequestStatus status) {
        this.id = id;
        this.equipment = equipment;
        this.requester = requester;
        this.purpose = purpose;
        this.requestedAt = requestedAt;
        this.status = status;
    }

    /**
     * Constructor for creating new entry requests without specifying an ID or
     * creation timestamp.
     *
     * @param equipment   associated equipment
     * @param requester   requesting person
     * @param purpose     purpose of the request
     * @param status      current status
     */
    public EntryRequest(Equipment equipment, Person requester, String purpose, RequestStatus status) {
        this.id = null;
        this.equipment = equipment;
        this.requester = requester;
        this.purpose = purpose;
        this.requestedAt = null;
        this.status = status;
    }

    /** @return request ID. */
    public Long getId() {
        return id;
    }

    /** @param id sets the request ID. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return associated equipment. */
    public Equipment getEquipment() {
        return equipment;
    }

    /** @param equipment sets the associated equipment. */
    public void setEquipment(Equipment equipment) {
        this.equipment = equipment;
    }

    /** @return the person who requested the entry. */
    public Person getRequester() {
        return requester;
    }

    /** @param requester sets the requesting person. */
    public void setRequester(Person requester) {
        this.requester = requester;
    }

    /** @return purpose of the request. */
    public String getPurpose() {
        return purpose;
    }

    /** @param purpose sets the purpose of the request. */
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    /** @return timestamp when the request was created. */
    public LocalDateTime getRequestedAt() {
        return requestedAt;
    }

    /** @param requestedAt sets the creation timestamp. */
    public void setRequestedAt(LocalDateTime requestedAt) {
        this.requestedAt = requestedAt;
    }

    /** @return current request status. */
    public RequestStatus getStatus() {
        return status;
    }

    /** @param status sets the request status. */
    public void setStatus(RequestStatus status) {
        this.status = status;
    }

    /**
     * Returns a textual representation of the entry request, including all fields.
     */
    @Override
    public String toString() {
        return "EntryRequest {id=" + id +
           ", equipment=" + equipment +
           ", requester=" + requester +
           ", purpose='" + purpose + "'" +
           ", requestedAt=" + requestedAt +
           ", status='" + status + "'" +
           "}";
    }

}
