package com.prototype.model.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.prototype.model.enums.EquipmentStatus;
import com.prototype.model.enums.EquipmentType;
import com.prototype.model.enums.FrequencyType;

/**
 * Base abstract entity that represents a generic equipment unit managed by the
 * system. This class provides the shared structure and attributes for all
 * equipment types (e.g., technological, medical, biomedical), while allowing
 * specialized subclasses to extend it.
 *
 * <p>
 * The inheritance strategy is {@code JOINED}, meaning each subclass has its
 * own table while the common attributes remain in the {@code equipments} table.
 * </p>
 *
 * <p>
 * This entity includes general descriptive information such as serial number,
 * brand, model, classification type, operational status, the stored image
 * reference, and the provider associated with the equipment.
 * </p>
 */
@Entity
@Table(name = "equipments")
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class Equipment {

    /**
     * Automatically generated identifier for the equipment.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Serial number assigned to the equipment. Cannot be null.
     */
    @Column(nullable = false)
    private String serial;

    /**
     * Brand or manufacturer of the equipment.
     */
    @Column(nullable = false)
    private String brand;

    /**
     * Model name or reference of the equipment.
     */
    @Column(nullable = false)
    private String model;

    /**
     * General classification of the equipment (computing, medical,
     * laboratory, audiovisual, etc.).
     */
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private EquipmentType type;

    /**
     * Operational state of the equipment (new, in use, under maintenance, etc.).
     */
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private EquipmentStatus state;

    /**
     * Path or identifier of the stored image associated with the equipment.
     */
    @Column(name = "image_path", nullable = false)
    private String imagePath;

    /**
     * Supplier associated with this equipment. This field is optional.
     * 
     * <p>
     * Loaded lazily to avoid unnecessary fetch operations.
     * </p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_provider", nullable = false)
    private Provider provider;

    /**
     * List of entry requests made for this equipment. Represents the one-to-many
     * relationship between equipment and its authorization requests.
     */
    @OneToMany(mappedBy = "equipment", cascade = {CascadeType.MERGE,CascadeType.REFRESH,CascadeType.REMOVE})
    private List<EntryRequest> entryRequests;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private FrequencyType frequencyType;

    /**
     * Default constructor required by JPA.
     */
    public Equipment() {
    }

    /**
     * Deprecated constructor including the ID.
     *
     * <p>
     * Kept only for compatibility with previous initialization patterns. New
     * equipment instances should rely on constructors where the ID is generated by
     * the persistence layer.
     * </p>
     */
    @Deprecated
    public Equipment(Long id, String serial, String brand, String model, EquipmentType type,
            EquipmentStatus state, Provider provider) {
        this.id = id;
        this.serial = serial;
        this.brand = brand;
        this.model = model;
        this.type = type;
        this.state = state;
        this.provider = provider;
        this.entryRequests = new ArrayList<>();
    }

    /**
     * Constructor for creating equipment instances without specifying an ID.
     * The ID will be generated by the database.
     *
     * @param serial    equipment serial number
     * @param brand     manufacturer or brand
     * @param model     model name
     * @param type      general classification of the equipment
     * @param state     operational status
     * @param imagePath reference to the stored image
     * @param provider  supplier associated with the equipment
     */
    public Equipment(String serial, String brand, String model, EquipmentType type,
            EquipmentStatus state, String imagePath, Provider provider) {
        this.id = null;
        this.serial = serial;
        this.brand = brand;
        this.model = model;
        this.type = type;
        this.state = state;
        this.provider = provider;
        this.imagePath = imagePath;
    }

    /** @return equipment ID. */
    public Long getId() {
        return id;
    }

    /** @param id sets the equipment ID. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return equipment serial number. */
    public String getSerial() {
        return serial;
    }

    /** @param serial sets the equipment serial number. */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /** @return equipment brand. */
    public String getBrand() {
        return brand;
    }

    /** @param brand sets the equipment brand. */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /** @return equipment model. */
    public String getModel() {
        return model;
    }

    /** @param model sets the equipment model. */
    public void setModel(String model) {
        this.model = model;
    }

    /** @return equipment type. */
    public EquipmentType getType() {
        return type;
    }

    /** @param type sets the equipment type. */
    public void setType(EquipmentType type) {
        this.type = type;
    }

    /** @return current equipment state. */
    public EquipmentStatus getState() {
        return state;
    }

    /** @param state updates the equipment state. */
    public void setState(EquipmentStatus state) {
        this.state = state;
    }

    /** @return path or identifier of the equipment image. */
    public String getImagePath() {
        return imagePath;
    }

    /** @param imagePath sets the equipment image path. */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    /** @return provider associated with the equipment. */
    public Provider getProvider() {
        return provider;
    }

    /** @param provider sets the equipment provider. */
    public void setProvider(Provider provider) {
        this.provider = provider;
    }

    /** @return list of entry requests associated with this equipment. */
    public List<EntryRequest> getEntryRequests() {
        return entryRequests;
    }

    /**
     * Adds a new entry request to the equipment.
     */
    public void addEntryRequests(EntryRequest entryRequest) {
        entryRequests.add(entryRequest);
    }

    /**
     * Removes an entry request from the equipment.
     */
    public void removeEntryRequests(EntryRequest entryRequest) {
        entryRequests.remove(entryRequest);
    }

    public void setFrecuencyType(FrequencyType frequencyType) {
        this.frequencyType = frequencyType;
    }

    public FrequencyType getFrequencyType() {
        return frequencyType;
    }

    /**
     * Returns a textual representation of the equipment, including its basic
     * attributes and the number of associated entry requests.
     */
    @Override
    public String toString() {
        return "Equipment {id=" + id +
                ", serial='" + serial + "'" +
                ", brand='" + brand + "'" +
                ", model='" + model + "'" +
                ", type='" + type + "'" +
                ", state='" + state + "'" +
                ", imagePath='" + imagePath + "'" +
                ", provider=" + provider +
                ", entryRequests=" + entryRequests.size() +
                "}";
    }

}
