package com.prototype.model.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.prototype.model.enums.Role;

/**
 * Entity that represents a person interacting with the system. A person may act
 * as a requester of entry authorizations and is identified by a full name and
 * document number.
 *
 * <p>This entity is stored in the {@code people} table and contains the basic
 * personal and role-related information necessary for access control and
 * auditing processes.</p>
 */
@Entity
@Table(name = "people")
public class Person {

    /**
     * Automatically generated identifier for the person.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full name of the person.
     */
    @Column(name = "full_name", nullable = false)
    private String fullName;

    /**
     * Document or identification number associated with the person.
     */
    @Column(nullable = false)
    private String document;

    /**
     * Role assigned to the person (e.g., ADMIN, DOCTOR, NURSE, WATCHMAN, etc.).
     */
    @Enumerated(EnumType.STRING)
    private Role role;

    /**
     * List of entry requests submitted by this person.
     *
     * <p>This represents the one-to-many relationship between a requester
     * and their corresponding entry requests.</p>
     */
    @OneToMany(mappedBy = "requester",cascade = {CascadeType.REMOVE,CascadeType.REFRESH,CascadeType.MERGE})
    private List<EntryRequest> entryRequests;

    /**
     * Default constructor required by JPA.
     */
    public Person() {
    }

    /**
     * Deprecated constructor including the ID.
     *
     * <p>Retained for compatibility. IDs should be automatically generated
     * by the persistence layer in new instances.</p>
     *
     * @param id        person ID
     * @param fullName  full name of the person
     * @param document  document or identification number
     * @param role      assigned role
     */
    @Deprecated
    public Person(Long id, String fullName, String document, Role role) {
        this.id = id;
        this.fullName = fullName;
        this.document = document;
        this.role = role;
        this.entryRequests = new ArrayList<>();
    }

    /**
     * Constructor used for creating new person records without specifying an ID.
     * The ID will be generated by the database.
     *
     * @param fullName  full name of the person
     * @param document  document or identification number
     * @param role      assigned role
     */
    public Person(String fullName, String document, Role role) {
        this.id = null;
        this.fullName = fullName;
        this.document = document;
        this.role = role;
        this.entryRequests = new ArrayList<>();
    }

    /** @return person ID. */
    public Long getId() {
        return id;
    }

    /** @param id sets the person ID. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the person's full name. */
    public String getFullName() {
        return fullName;
    }

    /** @param fullName sets the person's full name. */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /** @return the document or identification number. */
    public String getDocument() {
        return document;
    }

    /** @param document sets the document or identification number. */
    public void setDocument(String document) {
        this.document = document;
    }

    /** @return the role assigned to the person. */
    public Role getRole() {
        return role;
    }

    /** @param role updates the person's role. */
    public void setRole(Role role) {
        this.role = role;
    }

    /** @return list of entry requests made by this person. */
    public List<EntryRequest> getEntryRequests() {
        return entryRequests;
    }

    /** @param entryRequests sets the list of entry requests. */
    public void setEntryRequests(List<EntryRequest> entryRequests) {
        this.entryRequests = entryRequests;
    }

    /**
     * Returns a textual representation of the person, including the number of
     * associated entry requests.
     */
    @Override
    public String toString() {
        return "Person {id=" + id +
           ", fullName='" + fullName + "'" +
           ", document='" + document + "'" +
           ", role='" + role + "'" +
           ", entryRequests=" + entryRequests.size() +
           "}";
    }
}
