package com.prototype.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.prototype.model.enums.EquipmentStatus;
import com.prototype.model.enums.EquipmentType;

/**
 * Entity that represents a technological equipment item within the system.
 *
 * <p>This class extends {@link Equipment} and specializes it by adding
 * attributes relevant to computing and IT devices, such as operating system
 * information and RAM capacity.</p>
 *
 * <p>Instances of this entity are stored in the {@code Tech_equipments} table
 * as part of the joined inheritance hierarchy.</p>
 */
@Entity
@Table(name = "Tech_equipments")
public class TechEquipment extends Equipment {

    /**
     * Operating system installed on the technological device.
     */
    @Column(nullable = false)
    private String os;

    /**
     * RAM capacity of the device, expressed in gigabytes (GB).
     */
    @Column(nullable = false)
    private int ramGB;

    /**
     * Default constructor required by JPA.
     */
    public TechEquipment() {
    }


    /**
     * Constructor for creating new technological equipment entries without
     * specifying an ID. The ID will be automatically generated by the database.
     *
     * @param serial    serial number
     * @param brand     device brand
     * @param model     device model
     * @param type      equipment type
     * @param state     equipment state
     * @param imagePath image path or reference
     * @param provider  equipment provider
     * @param os        operating system
     * @param ramGB     RAM capacity in gigabytes
     */
    public TechEquipment(String serial, String brand, String model, EquipmentType type,
            EquipmentStatus state, String imagePath, Provider provider,
            String os, int ramGB) {
        super(serial, brand, model, type, state, imagePath, provider);
        this.os = os;
        this.ramGB = ramGB;
    }

    /** @return operating system of the device. */
    public String getOs() {
        return os;
    }

    /** @param os sets the operating system. */
    public void setOs(String os) {
        this.os = os;
    }

    /** @return RAM capacity in gigabytes. */
    public int getRamGB() {
        return ramGB;
    }

    /** @param ramGB sets the RAM capacity. */
    public void setRamGB(int ramGB) {
        this.ramGB = ramGB;
    }

    /**
     * Returns a textual representation of the technological equipment, combining
     * inherited attributes with the OS and RAM details.
     */
    @Override
    public String toString() {
        return super.toString() + " TechEquipment {os='" + os +
           "', ramGB='" + ramGB + "'}";
    }

}
